/* runner.mjs — the staff's brains. Every few minutes, any thread whose newest message is NOT from
 * its own staffer gets a reply, generated by a model holding that staffer's persona, the tail
 * of the thread, and the computer's tools. Bounded loop (MAX_ROUNDS) and bounded staff per tick,
 * and every reply lands through appendToThread — so claim verification polices the runner exactly
 * as it polices any other sender.
 *
 * BRING YOUR OWN MODEL. This speaks the Anthropic Messages API shape (`POST` with `x-api-key` +
 * `anthropic-version`, tools declared with `input_schema`), which several providers implement, so
 * BRAIN_URL can point at Anthropic or at any Anthropic-compatible endpoint — including free tiers.
 * Raw fetch rather than an SDK, deliberately: the endpoint is yours to choose, and a Worker should
 * not carry a client library to make one POST.
 *
 * Config (see wrangler.toml and README):
 *   BRAIN_API_KEY   secret  — the key for whatever endpoint you point at
 *   BRAIN_URL       var     — messages endpoint (default: Anthropic's)
 *   BRAIN_MODEL     var     — model id; required, no default worth guessing for you
 *   TAVILY_API_KEY  secret  — optional; gives the staff web_search (tavily.com free tier works)
 *   CF_BR_TOKEN     secret  — optional; gives the staff browser_visit via Cloudflare Browser
 *   CF_BR_ACCOUNT   var     — your Cloudflare account id, required alongside CF_BR_TOKEN
 *
 * Prompt doctrine: about twenty lines of system prompt, and no more. A staffer that needs
 * three pages of instructions to answer its own chat thread is a design problem, not a prompt one.
 */

const DEFAULT_BRAIN_URL = 'https://api.anthropic.com/v1/messages';
const MAX_ROUNDS = 6;          // tool rounds per reply
const MAX_STAFF_PER_TICK = 6;  // one full default-team round per tick — delegation chains crawl at 2 (brain calls are wall-clock, not CPU)

const RUNNER_TOOLS = [
  { name: 'fs_read', description: 'Read a file from the shared computer.', input_schema: { type: 'object', properties: { path: { type: 'string' } }, required: ['path'] } },
  { name: 'fs_list', description: 'List files under a prefix on the shared computer.', input_schema: { type: 'object', properties: { prefix: { type: 'string' } } } },
  { name: 'fs_write', description: 'Write/overwrite a text file on the shared computer.', input_schema: { type: 'object', properties: { path: { type: 'string' }, content: { type: 'string' } }, required: ['path', 'content'] } },
  { name: 'log_activity', description: 'Log what you are doing right now (shows on your screen panel).', input_schema: { type: 'object', properties: { action: { type: 'string' }, detail: { type: 'string' } }, required: ['action'] } },
  { name: 'web_search', description: 'Search the live web. Returns top results with titles, URLs and snippets. Use for research, competitor reads, fact checks.', input_schema: { type: 'object', properties: { query: { type: 'string' } }, required: ['query'] } },
  { name: 'web_fetch', description: 'Quick read of a URL (no JS, HTML stripped, capped). Cheapest way to read a plain page; download by fetching then fs_write.', input_schema: { type: 'object', properties: { url: { type: 'string' } }, required: ['url'] } },
  { name: 'browser_visit', description: 'Open a page in YOUR own Chrome (a real browser - runs JS). You get the page back as clean markdown, and a screenshot of what you saw lands on your monitor so the boss can watch you browse. Use for JS-heavy pages or anything worth showing; web_fetch is cheaper for plain text.', input_schema: { type: 'object', properties: { url: { type: 'string' } }, required: ['url'] } },
  { name: 'list_team', description: 'See your teammates: names, roles, what each is best at. Use before delegating.', input_schema: { type: 'object', properties: {} } },
  { name: 'message_teammate', description: 'Send a message to a teammate. Use to DELEGATE work that fits their charge better than yours (name concrete shared/ paths so their work is verifiable), or to REPORT BACK on work they gave you. They answer in their own time.', input_schema: { type: 'object', properties: { to: { type: 'string', description: 'teammate name from list_team' }, body: { type: 'string' } }, required: ['to', 'body'] } },
];

function systemPrompt(staffer) {
  return `You are ${staffer.screen_name}, an AI staffer at a company. Your charge: ${staffer.bio}.
You are talking with your team in a private chat. The newest message is addressed to you.

Rules:
- Be terse and concrete. You are a coworker, not an assistant: no "How can I help", no filler.
- PLAIN TEXT only - no markdown (**bold**, ##headers). Dashes for lists are fine. Speak directly
  to the sender; never restate their message or write meta-lines like "a new member joined".
- If the message is a work order naming files (shared/...), USE YOUR TOOLS: read the files, do the
  work, write results back, log_activity as you go. Only claim "done" if you actually wrote the fix.
- If you cannot complete something, say exactly what you did and what blocked you. Never bluff:
  the platform verifies file changes and publicly stamps false claims.
- If the message is a question or chat, just answer it well. No tools needed.
- You have a browser: web_search finds things online, web_fetch reads a page. Research runs through
  them, never from memory; save anything worth keeping with fs_write (your files are yours).
- DELEGATING is two tool calls, no more: list_team once, then message_teammate with the work order
  (include a concrete shared/ file path so their work is verifiable). Then immediately reply to the
  team saying who you picked and why. Do not research the task yourself if you are delegating it.
- Finish with your reply to the team (plain text). That final text is what gets posted.`;
}

/* The staff's browser + search. Search = Tavily (their free tier is enough to start); fetch =
 * plain GET with the HTML stripped and a hard cap so one page can't blow the context. Both fail
 * soft with an ERROR string the model can read and route around. */
async function webSearch(env, query) {
  if (!query) return 'ERROR: query is required';
  if (!env.TAVILY_API_KEY) return 'ERROR: search is not configured on this computer yet';
  const r = await fetch('https://api.tavily.com/search', {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ api_key: env.TAVILY_API_KEY, query: query.slice(0, 300), max_results: 5 }),
    signal: AbortSignal.timeout(20000),
  });
  if (!r.ok) return `ERROR: search HTTP ${r.status}`;
  const d = await r.json();
  return (d.results || []).map((x) => `${x.title}\n${x.url}\n${String(x.content || '').slice(0, 300)}`).join('\n\n') || 'no results';
}
async function webFetch(url) {
  if (!/^https?:\/\//i.test(url)) return 'ERROR: url must start with http(s)://';
  let r;
  try {
    r = await fetch(url, { headers: { 'user-agent': 'StaffroomBot/1.0' }, signal: AbortSignal.timeout(20000), redirect: 'follow' });
  } catch (e) { return `ERROR: fetch failed - ${String(e?.message || e).slice(0, 120)}`; }
  if (!r.ok) return `ERROR: HTTP ${r.status} from ${url}`;
  const raw = (await r.text()).slice(0, 400000);
  const text = raw
    .replace(/<script[\s\S]*?<\/script>/gi, ' ').replace(/<style[\s\S]*?<\/style>/gi, ' ')
    .replace(/<[^>]+>/g, ' ').replace(/&nbsp;/g, ' ').replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
    .replace(/\s{3,}/g, '\n').trim();
  return text.slice(0, 8000) || '(page had no readable text)';
}

/* browser_visit — each staffer's own Chrome, via Cloudflare's Browser Rendering REST API (Workers
 * Paid includes a monthly allowance; the REST quick-actions bill duration only). The model's eyes
 * are the MARKDOWN (no vision model needed); the screenshot is for the human's monitor pane.
 * Frugal by design: one markdown + one screenshot call per visit. */
async function browserVisit(env, who, tp, url) {
  if (!/^https?:\/\//i.test(url)) return 'ERROR: url must start with http(s)://';
  if (!env.CF_BR_TOKEN || !env.CF_BR_ACCOUNT) return 'ERROR: the office Chrome is not configured yet (set CF_BR_TOKEN and CF_BR_ACCOUNT)';
  const hdrs = { authorization: `Bearer ${env.CF_BR_TOKEN}`, 'content-type': 'application/json' };
  const base = `https://api.cloudflare.com/client/v4/accounts/${env.CF_BR_ACCOUNT}/browser-rendering`;
  let md = '';
  try {
    const r = await fetch(`${base}/markdown`, { method: 'POST', headers: hdrs, body: JSON.stringify({ url }), signal: AbortSignal.timeout(45000) });
    const d = await r.json().catch(() => ({}));
    if (!d.success) return `ERROR: browser could not open ${url} (${JSON.stringify(d.errors || d).slice(0, 150)})`;
    md = String(d.result || '').slice(0, 8000);
  } catch (e) { return `ERROR: browser failed - ${String(e?.message || e).slice(0, 120)}`; }
  // the monitor frame: best-effort, never blocks the read
  try {
    const s = await fetch(`${base}/screenshot`, { method: 'POST', headers: hdrs, body: JSON.stringify({ url, screenshotOptions: { type: 'png' }, viewport: { width: 1280, height: 800 } }), signal: AbortSignal.timeout(45000) });
    if (s.ok && (s.headers.get('content-type') || '').includes('image')) {
      const bytes = new Uint8Array(await s.arrayBuffer());
      if (bytes.length <= 4 * 1024 * 1024) await env.FS.put(`${tp}screens/${who}/latest.png`, bytes, { contentType: 'image/png' });
    }
  } catch {}
  return md || '(page had no readable text)';
}

async function callBrain(env, system, messages) {
  const r = await fetch(env.BRAIN_URL || DEFAULT_BRAIN_URL, {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      // Anthropic authenticates with x-api-key; some compatible endpoints expect a bearer token.
      // Sending both keeps one config working across providers.
      'x-api-key': env.BRAIN_API_KEY,
      'authorization': `Bearer ${env.BRAIN_API_KEY}`,
      'anthropic-version': '2023-06-01',
    },
    body: JSON.stringify({ model: env.BRAIN_MODEL, max_tokens: 1200, system, messages, tools: RUNNER_TOOLS }),
    signal: AbortSignal.timeout(90000),
  });
  if (!r.ok) throw new Error(`brain HTTP ${r.status}: ${(await r.text()).slice(0, 200)}`);
  return r.json();
}

/* One staffer answers their thread. deps = { runTool, postActivity, appendToThread, staff, tp } —
 * built by scopedDeps() in index.mjs, so every filesystem/feed/thread touch is already confined
 * to the right namespace. Only the keys this function reads directly need the prefix by hand. */
export async function respondForStaffer(env, deps, staffer) {
  const who = staffer.screen_name.toLowerCase();
  const tp = deps.tp || ''; // tenant prefix: '' = the root office
  const obj = await env.FS.get(`${tp}threads/${who}.jsonl`);
  if (!obj) return null;
  const msgs = (await obj.text()).split('\n').filter(Boolean).map((l) => JSON.parse(l));
  if (!msgs.length) return null;
  const last = msgs[msgs.length - 1];
  if (last.from === staffer.screen_name) return null; // already answered
  if (!last.body) return null;

  // double-reply lock: wake-on-send and the cron can race. First writer wins for ~2 minutes.
  const lockKey = `${tp}system-status/${who}`;
  const lock = await env.FS.get(lockKey);
  if (lock && Date.now() - Number(await lock.text()) < 120000) return null;
  await env.FS.put(lockKey, String(Date.now())); // doubles as the "working" indicator the UI shows

  // The thread tail as alternating turns: everyone else is "user", this staffer's own past
  // messages are "assistant". Names are prefixed because a thread can have several senders and
  // the role alone would lose track of who said what.
  const tail = msgs.slice(-12).map((m) => ({
    role: m.from === staffer.screen_name ? 'assistant' : 'user',
    content: `${m.from}: ${m.body}`.slice(0, 2000),
  }));
  // The Messages API requires the first message to be role=user; drop any leading assistant turns.
  while (tail.length && tail[0].role === 'assistant') tail.shift();
  if (!tail.length) { await env.FS.delete(lockKey); return null; }

  const convo = [...tail];
  let finalText = null;
  for (let round = 0; round < MAX_ROUNDS; round++) {
    const res = await callBrain(env, systemPrompt(staffer), convo);
    const toolUses = (res.content || []).filter((c) => c.type === 'tool_use');
    const texts = (res.content || []).filter((c) => c.type === 'text').map((c) => c.text).join('\n').trim();
    if (!toolUses.length) { finalText = texts || null; break; }
    convo.push({ role: 'assistant', content: res.content });
    const results = [];
    for (const tu of toolUses) {
      let out;
      try {
        if (tu.name === 'log_activity') out = await deps.postActivity(env, { employee: who, action: tu.input?.action, detail: tu.input?.detail });
        else if (tu.name === 'web_search') out = await webSearch(env, String(tu.input?.query || ''));
        else if (tu.name === 'web_fetch') out = await webFetch(String(tu.input?.url || ''));
        else if (tu.name === 'browser_visit') {
          out = await browserVisit(env, who, tp, String(tu.input?.url || ''));
          if (!String(out).startsWith('ERROR')) await deps.postActivity(env, { employee: who, action: `Browsing ${String(tu.input?.url || '').slice(0, 80)}`, detail: 'opened in my Chrome - frame on my monitor' }).catch(() => {});
        }
        else if (tu.name === 'list_team') out = JSON.stringify(deps.staff.map((s) => ({ name: s.screen_name, charge: s.bio })));
        else if (tu.name === 'message_teammate') {
          const target = deps.staff.find((s) => s.screen_name.toLowerCase() === String(tu.input?.to || '').toLowerCase());
          if (!target) out = `ERROR: no teammate named "${tu.input?.to}" - use list_team`;
          else if (target.screen_name === staffer.screen_name) out = 'ERROR: that is you';
          else {
            await deps.appendToThread(env, target.screen_name.toLowerCase(), staffer.screen_name, String(tu.input?.body || '').slice(0, 4000));
            out = `delivered to ${target.screen_name} - they will answer in their own thread; check back or ask them for the report`;
          }
        }
        else out = await deps.runTool(env, tu.name, tu.input || {});
      } catch (e) { out = `ERROR: ${e?.msg || e?.message || e}`; }
      results.push({ type: 'tool_result', tool_use_id: tu.id, content: String(out).slice(0, 4000) });
    }
    convo.push({ role: 'user', content: results });
    if (round === MAX_ROUNDS - 1) finalText = texts || 'Ran out of tool rounds — here is where I got to; ask me to continue.';
  }
  if (!finalText) { await env.FS.delete(lockKey); return null; }
  const verify = await deps.appendToThread(env, who, staffer.screen_name, finalText);
  await env.FS.delete(lockKey); // working indicator off
  return { staffer: staffer.screen_name, replied: true, verify };
}

export async function runTick(env, deps) {
  if (!env.BRAIN_API_KEY) return [{ error: 'BRAIN_API_KEY is not set — the staff have no brains yet' }];
  if (!env.BRAIN_MODEL) return [{ error: 'BRAIN_MODEL is not set — pick a model for your endpoint' }];
  const out = [];
  for (const staffer of deps.staff) {
    if (out.length >= MAX_STAFF_PER_TICK) break;
    try {
      const r = await respondForStaffer(env, deps, staffer);
      if (r) out.push(r);
    } catch (e) {
      out.push({ staffer: staffer.screen_name, error: String(e?.message || e).slice(0, 200) });
    }
  }
  return out;
}
