/* runner.mjs — the staff's brains. Every few minutes, any thread whose newest message is NOT from
 * its own staff member gets a reply, generated by a model holding that member's persona, the tail
 * of the thread, and the computer's filesystem tools. Bounded loop (MAX_ROUNDS) and bounded staff
 * per tick, and every reply lands through appendToThread — so claim verification polices the
 * runner exactly as it polices any other sender.
 *
 * BRING YOUR OWN MODEL. This speaks the Anthropic Messages API shape (`POST` with `x-api-key` +
 * `anthropic-version`, tools declared with `input_schema`), which several providers implement, so
 * BRAIN_URL can point at Anthropic or at any Anthropic-compatible endpoint — including free tiers.
 * Raw fetch rather than an SDK, deliberately: the endpoint is yours to choose, and a Worker should
 * not carry a client library to make one POST.
 *
 * Config (see wrangler.toml and README):
 *   BRAIN_API_KEY  secret   — the key for whatever endpoint you point at
 *   BRAIN_URL      var      — messages endpoint (default: Anthropic's)
 *   BRAIN_MODEL    var      — model id; required, no default worth guessing for you
 *
 * Prompt doctrine: about twenty lines of system prompt, and no more. A staff member that needs
 * three pages of instructions to answer its own chat thread is a design problem, not a prompt one.
 */

const DEFAULT_BRAIN_URL = 'https://api.anthropic.com/v1/messages';
const MAX_ROUNDS = 6;          // tool rounds per reply
const MAX_STAFF_PER_TICK = 2;  // keeps one cron tick inside its time and cost budget

const RUNNER_TOOLS = [
  { name: 'fs_read', description: 'Read a file from the shared computer.', input_schema: { type: 'object', properties: { path: { type: 'string' } }, required: ['path'] } },
  { name: 'fs_list', description: 'List files under a prefix on the shared computer.', input_schema: { type: 'object', properties: { prefix: { type: 'string' } } } },
  { name: 'fs_write', description: 'Write/overwrite a text file on the shared computer.', input_schema: { type: 'object', properties: { path: { type: 'string' }, content: { type: 'string' } }, required: ['path', 'content'] } },
  { name: 'log_activity', description: 'Log what you are doing right now (shows on your screen panel).', input_schema: { type: 'object', properties: { action: { type: 'string' }, detail: { type: 'string' } }, required: ['action'] } },
];

function systemPrompt(staffer) {
  return `You are ${staffer.screen_name}, an AI staffer at a company. Your charge: ${staffer.bio}.
You are talking with your team in a private chat. The newest message is addressed to you.

Rules:
- Be terse and concrete. You are a coworker, not an assistant: no "How can I help", no filler.
- If the message is a work order naming files (shared/...), USE YOUR TOOLS: read the files, do the
  work, write results back, log_activity as you go. Only claim "done" if you actually wrote the fix.
- If you cannot complete something, say exactly what you did and what blocked you. Never bluff:
  the platform verifies file changes and publicly stamps false claims.
- If the message is a question or chat, just answer it well. No tools needed.
- Finish with your reply to the team (plain text). That final text is what gets posted.`;
}

async function callBrain(env, system, messages) {
  const r = await fetch(env.BRAIN_URL || DEFAULT_BRAIN_URL, {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      // Anthropic authenticates with x-api-key; some compatible endpoints expect a bearer token.
      // Sending both keeps one config working across providers.
      'x-api-key': env.BRAIN_API_KEY,
      'authorization': `Bearer ${env.BRAIN_API_KEY}`,
      'anthropic-version': '2023-06-01',
    },
    body: JSON.stringify({ model: env.BRAIN_MODEL, max_tokens: 1200, system, messages, tools: RUNNER_TOOLS }),
    signal: AbortSignal.timeout(90000),
  });
  if (!r.ok) throw new Error(`brain HTTP ${r.status}: ${(await r.text()).slice(0, 200)}`);
  return r.json();
}

/* One staff member answers their thread. deps = { runTool, postActivity, appendToThread, staff } */
export async function respondForStaffer(env, deps, staffer) {
  const who = staffer.screen_name.toLowerCase();
  const obj = await env.FS.get(`threads/${who}.jsonl`);
  if (!obj) return null;
  const msgs = (await obj.text()).split('\n').filter(Boolean).map((l) => JSON.parse(l));
  if (!msgs.length) return null;
  const last = msgs[msgs.length - 1];
  if (last.from === staffer.screen_name) return null; // already answered
  if (!last.body) return null;

  // The thread tail as alternating turns: everyone else is "user", this member's own past
  // messages are "assistant". Names are prefixed because a thread can have several senders and
  // the role alone would lose track of who said what.
  const tail = msgs.slice(-12).map((m) => ({
    role: m.from === staffer.screen_name ? 'assistant' : 'user',
    content: `${m.from}: ${m.body}`.slice(0, 2000),
  }));
  // The Messages API requires the first message to be role=user; drop any leading assistant turns.
  while (tail.length && tail[0].role === 'assistant') tail.shift();
  if (!tail.length) return null;

  const convo = [...tail];
  let finalText = null;
  for (let round = 0; round < MAX_ROUNDS; round++) {
    const res = await callBrain(env, systemPrompt(staffer), convo);
    const toolUses = (res.content || []).filter((c) => c.type === 'tool_use');
    const texts = (res.content || []).filter((c) => c.type === 'text').map((c) => c.text).join('\n').trim();
    if (!toolUses.length) { finalText = texts || null; break; }
    convo.push({ role: 'assistant', content: res.content });
    const results = [];
    for (const tu of toolUses) {
      let out;
      try {
        if (tu.name === 'log_activity') out = await deps.postActivity(env, { employee: who, action: tu.input?.action, detail: tu.input?.detail });
        else out = await deps.runTool(env, tu.name, tu.input || {});
      } catch (e) { out = `ERROR: ${e?.msg || e?.message || e}`; }
      results.push({ type: 'tool_result', tool_use_id: tu.id, content: String(out).slice(0, 4000) });
    }
    convo.push({ role: 'user', content: results });
    if (round === MAX_ROUNDS - 1) finalText = texts || 'Ran out of tool rounds — here is where I got to; ask me to continue.';
  }
  if (!finalText) return null;
  const verify = await deps.appendToThread(env, who, staffer.screen_name, finalText, true);
  return { staffer: staffer.screen_name, replied: true, verify };
}

export async function runTick(env, deps) {
  if (!env.BRAIN_API_KEY) return [{ error: 'BRAIN_API_KEY is not set — the staff have no brains yet' }];
  if (!env.BRAIN_MODEL) return [{ error: 'BRAIN_MODEL is not set — pick a model for your endpoint' }];
  const out = [];
  for (const staffer of deps.staff) {
    if (out.length >= MAX_STAFF_PER_TICK) break;
    try {
      const r = await respondForStaffer(env, deps, staffer);
      if (r) out.push(r);
    } catch (e) {
      out.push({ staffer: staffer.screen_name, error: String(e?.message || e).slice(0, 200) });
    }
  }
  return out;
}
