/* runner.mjs — the staff's brains. Every few minutes: any thread whose newest message is NOT from
 * its staffer gets a response, generated by a FREE model (z.ai GLM, Anthropic-compatible API)
 * holding the staffer's persona + the thread tail + the computer's fs tools. Bounded loop
 * (MAX_ROUNDS), bounded staff per tick, and every reply lands through appendToThread — so the
 * claim-verification stamps police the runner exactly like they police everyone else.
 * Context doctrine (bot-seat experiment 2026-08-14): ~20 lines of system prompt. No more. */

import { secp256k1 } from '@noble/curves/secp256k1.js';
import { keccak_256 } from '@noble/hashes/sha3.js';

const ZAI = 'https://api.z.ai/api/anthropic/v1/messages';
const MODEL = 'glm-4.5-flash';
const MAX_ROUNDS = 12;
// the office's strong fallback brain: escalation retries after a fabrication stamp run here
// (free Groq tier - 8000 TPM, handled by the 429 backoff in callBrain)
const STRONG_FALLBACK = { url: 'https://api.groq.com/openai/v1/chat/completions', model: 'openai/gpt-oss-120b', key: '' };
const MAX_STAFF_PER_TICK = 6; // one full team round per tick — delegation chains crawl at 2 (brain calls are wall-clock, not CPU)

const RUNNER_TOOLS = [
  { name: 'fs_read', description: 'Read a file from the office computer.', input_schema: { type: 'object', properties: { path: { type: 'string' } }, required: ['path'] } },
  { name: 'fs_list', description: 'List files under a prefix on the office computer.', input_schema: { type: 'object', properties: { prefix: { type: 'string' } } } },
  { name: 'fs_write', description: 'Write/overwrite a text file on the office computer.', input_schema: { type: 'object', properties: { path: { type: 'string' }, content: { type: 'string' } }, required: ['path', 'content'] } },
  { name: 'log_activity', description: 'Log what you are doing right now (shows on your screen panel).', input_schema: { type: 'object', properties: { action: { type: 'string' }, detail: { type: 'string' } }, required: ['action'] } },
  { name: 'web_search', description: 'Search the live web. Returns top results with titles, URLs and snippets. Use for research, competitor reads, fact checks.', input_schema: { type: 'object', properties: { query: { type: 'string' } }, required: ['query'] } },
  { name: 'web_fetch', description: 'Quick read of a URL (no JS, HTML stripped, capped). Cheapest way to read a plain page; download by fetching then fs_write.', input_schema: { type: 'object', properties: { url: { type: 'string' } }, required: ['url'] } },
  { name: 'browser_visit', description: 'Open a page in YOUR own Chrome (a real browser - runs JS, carries YOUR saved logins). You get the page back as clean markdown, and a screenshot lands on your monitor so the boss can watch. web_fetch is cheaper for plain public text.', input_schema: { type: 'object', properties: { url: { type: 'string' } }, required: ['url'] } },
  { name: 'http_request', description: 'Direct HTTP call to ANY url - GET/POST/PUT/DELETE, optional JSON body and extra headers. For public APIs that have no connector (connected services still go through api_call, which carries their auth). Raw response text comes back, capped. Never put secrets in the url, body or headers.', input_schema: { type: 'object', properties: { url: { type: 'string' }, method: { type: 'string', description: 'GET (default), POST, PUT or DELETE' }, body: { type: 'string', description: 'request body, usually JSON' }, headers: { type: 'object', description: 'extra headers, e.g. {"content-type":"application/json"}' } }, required: ['url'] } },
  { name: 'login_desk', description: "Open YOUR browser for the boss to sign into a service by hand (their login stays on YOUR computer only). Returns a live-control link for them. Use when a job needs an account and your jar has no login for it.", input_schema: { type: 'object', properties: { service: { type: 'string', description: 'what to sign into, e.g. youtube.com' } } } },
  { name: 'collect_login', description: 'After the boss says they signed in on your login desk, collect the cookies into your own jar. From then on browser_visit is signed in there.', input_schema: { type: 'object', properties: {} } },
  { name: 'list_team', description: 'See your teammates: names, roles, what each is best at. Use before delegating.', input_schema: { type: 'object', properties: {} } },
  { name: 'message_teammate', description: 'Send a message to a teammate. Use to DELEGATE work that fits their charge better than yours (name concrete shared/ paths so their work is verifiable), or to REPORT BACK on work they gave you. They answer in their own time.', input_schema: { type: 'object', properties: { to: { type: 'string', description: 'teammate name from list_team' }, body: { type: 'string' } }, required: ['to', 'body'] } },
  { name: 'ask_user', description: 'Ask the boss a question with 2-4 clickable choices. Use when a decision is genuinely theirs (taste, budget, direction) - never for things you can find out yourself. This ENDS your turn; their click arrives as their next message.', input_schema: { type: 'object', properties: { question: { type: 'string' }, options: { type: 'array', items: { type: 'string' }, description: '2-4 short choices' } }, required: ['question', 'options'] } },
  { name: 'calendar_read', description: "Read the boss's connected calendar (next days of events). Uses their Google connection if present, else their ICS link.", input_schema: { type: 'object', properties: { days: { type: 'number', description: 'lookahead days, default 7' } } } },
  { name: 'gmail_unread', description: "Read the boss's unread Gmail (from/subject/snippet, read-only). Needs their Google connection; tell them to click Connect Google in the panel if missing.", input_schema: { type: 'object', properties: { limit: { type: 'number', description: 'max messages, default 8' } } } },
  { name: 'yt_recent_comments', description: "List recent comments on the boss's YouTube channel (author, text, video, comment id). Needs their Google connection with YouTube access.", input_schema: { type: 'object', properties: { limit: { type: 'number', description: 'max threads, default 15' } } } },
  { name: 'yt_reply', description: "Reply to a YouTube comment AS the boss's channel. parent_id comes from yt_recent_comments. Keep replies short, warm, human - never spammy, skip toxic bait.", input_schema: { type: 'object', properties: { parent_id: { type: 'string' }, text: { type: 'string' } }, required: ['parent_id', 'text'] } },
  { name: 'feed_read', description: 'Read an RSS/Atom feed - the connected default one, or any feed URL you pass.', input_schema: { type: 'object', properties: { url: { type: 'string', description: 'optional; defaults to the connected feed' } } } },
  { name: 'notify_boss', description: "Push a short note to the boss's phone (their connected ntfy topic). Use for finished work or something urgent - not chatter.", input_schema: { type: 'object', properties: { message: { type: 'string' } }, required: ['message'] } },
  { name: 'wallet_create', description: 'Create a NEW empty crypto wallet under a custom name (Base network). The key is stored in the office vault - you never see or reveal private keys. There is NO tool to move funds: transfers are human-only.', input_schema: { type: 'object', properties: { name: { type: 'string' } }, required: ['name'] } },
  { name: 'wallet_import', description: "Save a wallet the boss gives you (name + private key) so you can watch its balance. Recommend they use a FRESH key, not their main one. The key goes straight to the vault; never repeat it in chat.", input_schema: { type: 'object', properties: { name: { type: 'string' }, private_key: { type: 'string' } }, required: ['name', 'private_key'] } },
  { name: 'wallet_list', description: "List the office's saved wallets (and the boss's Bankr wallet if connected) with live Base ETH balances. Use to monitor balances.", input_schema: { type: 'object', properties: {} } },
  { name: 'api_call', description: "Call one of the boss's connected services (their Connectors panel lists them by name). method GET/POST/PUT/DELETE, path is appended to the service's base URL. Returns the raw response text.", input_schema: { type: 'object', properties: { connector: { type: 'string' }, method: { type: 'string' }, path: { type: 'string' }, body: { type: 'string', description: 'JSON body for POST/PUT' } }, required: ['connector', 'method', 'path'] } },
  { name: 'hire_staffer', description: 'Create a new AI staffer on this team (they get a desk immediately). Use AFTER a short ask_user wizard settled their role and name with the boss - never invent a teammate unprompted. Give every hire a dept and ONE narrow specialization: single-duty agents work, kitchen-sink agents fail.', input_schema: { type: 'object', properties: { name: { type: 'string' }, emoji: { type: 'string' }, bio: { type: 'string', description: 'their charge: what they are for, ≤140 chars' }, dept: { type: 'string', description: 'department tag, e.g. YouTube, Crypto, Ops' }, spec: { type: 'string', description: 'their ONE narrow specialization, ≤100 chars' } }, required: ['name', 'bio'] } },
  { name: 'set_routine', description: "Put recurring work on a teammate's (or your own) calendar, landing in their thread as a task. Daily: set hourUTC 0-23. More often: set every_hours 2-12 instead (e.g. 3 = every 3 hours). Use when the boss wants something recurring, or your combo needs a standing leg.", input_schema: { type: 'object', properties: { staffer: { type: 'string' }, hourUTC: { type: 'number' }, every_hours: { type: 'number', description: 'fire every N hours instead of daily' }, text: { type: 'string' } }, required: ['staffer', 'text'] } },
  { name: 'coworker_report', description: "Read a teammate's recent work: their last messages with verification verdicts. Judge who to trust with a job, or check delegated work without nagging.", input_schema: { type: 'object', properties: { name: { type: 'string' } }, required: ['name'] } },
  { name: 'repo_commit', description: "Commit a dated report to the company repo at company/agent-reports/<name>.md (the fleet's official trail). Only that folder - use it to file your routine reports where the whole company reads them.", input_schema: { type: 'object', properties: { path: { type: 'string', description: 'company/agent-reports/<name>.md' }, content: { type: 'string' }, message: { type: 'string', description: 'commit message' } }, required: ['path', 'content'] } },
  { name: 'repo_read', description: "Read a file from the company repo (company/... paths only): HEALTH-STATUS.md, fleet-status.json, IDEAS_BACKLOG.md, prior agent-reports. The repo is private - this is the only way to read it.", input_schema: { type: 'object', properties: { path: { type: 'string', description: 'company/...' } }, required: ['path'] } },
  { name: 'team_stats', description: "The office bench: per-staffer scorecard computed by the harness from real work - replies, tool calls, honesty stamps (verified/unverified), Auditor verdicts, last activity. Ground truth for employee reviews.", input_schema: { type: 'object', properties: {} } },
];

/* ── wallets: create/import/list only. Keys live at system/wallets/<acct>.json (ROOT namespace —
 * staffer fs tools cannot reach it) and NEVER travel back through chat. There is deliberately no
 * send/sign tool: moving money stays a human action (company law). Base RPC for balances. */
const hexOf = (b) => [...b].map((x) => x.toString(16).padStart(2, '0')).join('');
const bytesOf = (hex) => Uint8Array.from(hex.match(/.{2}/g).map((x) => parseInt(x, 16)));
const acctOf = (tp) => (tp ? (tp.match(/^tenants\/([a-f0-9]+)\//) || [])[1] : 'root');
function pkToAddress(pkHex) {
  const pub = secp256k1.getPublicKey(bytesOf(pkHex), false).slice(1);
  const addr = hexOf(keccak_256(pub).slice(-20));
  const hh = hexOf(keccak_256(new TextEncoder().encode(addr)));
  return '0x' + [...addr].map((c, i) => (parseInt(hh[i], 16) > 7 ? c.toUpperCase() : c)).join('');
}
async function walletStore(env, tp) {
  const o = await env.FS.get(`system/wallets/${acctOf(tp)}.json`);
  return o ? JSON.parse(await o.text()) : [];
}
async function walletSave(env, tp, list) { await env.FS.put(`system/wallets/${acctOf(tp)}.json`, JSON.stringify(list)); }
export async function walletCreate(env, tp, name) {
  name = String(name || '').trim().slice(0, 30);
  if (!name) return 'ERROR: give the wallet a name';
  const list = await walletStore(env, tp);
  if (list.length >= 10) return 'ERROR: wallet limit (10) reached';
  if (list.find((w) => w.name.toLowerCase() === name.toLowerCase())) return `ERROR: a wallet named "${name}" already exists`;
  const pk = hexOf((secp256k1.utils.randomSecretKey || secp256k1.utils.randomPrivateKey)());
  const address = pkToAddress(pk);
  list.push({ name, address, pk, created: new Date().toISOString(), imported: false });
  await walletSave(env, tp, list);
  return `created wallet "${name}" - ${address} (Base, empty). Its key is in the office vault; there is no way to move funds from chat.`;
}
export async function walletImport(env, tp, name, pkRaw) {
  name = String(name || '').trim().slice(0, 30);
  const pk = String(pkRaw || '').trim().replace(/^0x/i, '').toLowerCase();
  if (!name) return 'ERROR: give the wallet a name';
  if (!/^[0-9a-f]{64}$/.test(pk)) return 'ERROR: private key must be 64 hex chars';
  const list = await walletStore(env, tp);
  if (list.length >= 10) return 'ERROR: wallet limit (10) reached';
  if (list.find((w) => w.name.toLowerCase() === name.toLowerCase())) return `ERROR: a wallet named "${name}" already exists`;
  let address;
  try { address = pkToAddress(pk); } catch { return 'ERROR: that key does not derive a valid wallet'; }
  list.push({ name, address, pk, created: new Date().toISOString(), imported: true });
  await walletSave(env, tp, list);
  return `saved wallet "${name}" - ${address}. Reminder to the boss: use a fresh key for agent wallets, and never paste your main wallet's key anywhere.`;
}
export async function walletRows(env, tp) {
  const list = await walletStore(env, tp);
  const rows = list.map((w) => ({ name: w.name, address: w.address, imported: !!w.imported }));
  try {
    const c = await getConnectors(env, tp);
    if (c.bankr_api_key) {
      const r = await fetch('https://api.bankr.bot/agent/wallet', { headers: { 'x-api-key': c.bankr_api_key }, signal: AbortSignal.timeout(15000) });
      const d = await r.json().catch(() => ({}));
      const addr = d.address || d.evmAddress || d.wallet?.address || d.wallets?.[0]?.address || d.accountAddress;
      if (r.ok && addr) rows.push({ name: 'Bankr', address: addr, bankr: true });
      else if (!r.ok) rows.push({ name: 'Bankr', address: '(key rejected - check it in Connectors)', bankr: true, error: true });
    }
  } catch {}
  if (rows.length) {
    try {
      const batch = rows.map((w, i) => ({ jsonrpc: '2.0', id: i, method: 'eth_getBalance', params: [w.address, 'latest'] }));
      const r = await fetch('https://mainnet.base.org', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(batch), signal: AbortSignal.timeout(15000) });
      const res = await r.json();
      for (const item of Array.isArray(res) ? res : []) {
        if (rows[item.id] && item.result) rows[item.id].base_eth = (Number(BigInt(item.result)) / 1e18).toFixed(6);
      }
    } catch {}
  }
  return rows;
}
async function walletListText(env, tp) {
  const rows = await walletRows(env, tp);
  if (!rows.length) return 'no wallets yet - wallet_create makes a fresh one, or the boss can import/connect theirs in the Connectors panel';
  return rows.map((w) => `${w.name} - ${w.address} - ${w.base_eth ?? '?'} ETH (Base)${w.imported ? ' [imported]' : ''}${w.bankr ? ' [bankr]' : ''}`).join('\n');
}
async function apiCall(env, tp, cName, method, path, body) {
  const { custom = [] } = await getConnectors(env, tp);
  const c = custom.find((x) => x.name.toLowerCase() === String(cName || '').toLowerCase());
  if (!c) return `ERROR: no connected service named "${cName}"${custom.length ? ' - available: ' + custom.map((x) => x.name).join(', ') : ' - the boss has not connected any services yet'}`;
  const m = String(method || 'GET').toUpperCase();
  if (!['GET', 'POST', 'PUT', 'DELETE'].includes(m)) return 'ERROR: method must be GET/POST/PUT/DELETE';
  const url = c.base.replace(/\/$/, '') + (String(path).startsWith('/') ? path : '/' + path);
  if (!url.startsWith(c.base.replace(/\/$/, ''))) return 'ERROR: path escapes the service base';
  try {
    const r = await fetch(url, {
      method: m,
      headers: { [c.headerName || 'authorization']: c.headerValue || '', 'user-agent': 'StaffroomBot/1.0', ...(body ? { 'content-type': 'application/json' } : {}) },
      body: body || undefined,
      signal: AbortSignal.timeout(30000),
    });
    return `HTTP ${r.status}\n${(await r.text()).slice(0, 6000)}`;
  } catch (e) { return `ERROR: ${String(e?.message || e).slice(0, 150)}`; }
}

/* THE BENCH, ON REAL WORK (Anthony 2026-08-14: "after benchmarking there's always employee
 * reviews"): deterministic per-staffer scorecard computed from the actual threads - replies,
 * tools run, honesty stamps, audit verdicts, escalations. Code, not vibes; reviewers judge on top. */
export async function teamStats(env, tp) {
  const threads = await env.FS.list({ prefix: `${tp}threads/`, limit: 50 });
  const rows = {};
  for (const t of threads.objects) {
    const owner = t.key.slice(`${tp}threads/`.length).replace(/\.jsonl$/, '');
    const obj = await env.FS.get(t.key);
    if (!obj) continue;
    const msgs = (await obj.text()).split('\n').filter(Boolean).map((l) => JSON.parse(l));
    for (const m of msgs) {
      if (m.from === 'Anthony' || m.from === 'Auditor' || m.report) continue;
      if (m.from.toLowerCase() !== owner) continue;
      const r = (rows[m.from] ||= { replies: 0, tool_calls: 0, replies_with_tools: 0, verified: 0, unverified: 0, audit_ok: 0, audit_suspect: 0, last_active: '' });
      r.replies++;
      if (Array.isArray(m.actions)) { r.tool_calls += m.actions.length; if (m.actions.length) r.replies_with_tools++; }
      if (m.verify?.verdict === 'verified') r.verified++;
      if (m.verify?.verdict === 'unverified') r.unverified++;
      if (m.audit?.v === 'ok') r.audit_ok++;
      if (m.audit?.v === 'suspect') r.audit_suspect++;
      if (m.created_at > r.last_active) r.last_active = m.created_at;
    }
  }
  return rows;
}

/* Scoped repo trail: staffers commit dated reports to the company repo (fleet trail-law) and
 * NOTHING else - the path allowlist is the whole safety story. Uses the github connector's token. */
async function repoCommit(env, tp, path, content, message) {
  const { custom = [] } = await getConnectors(env, tp);
  const c = custom.find((x) => x.name.toLowerCase() === 'github');
  if (!c) return 'ERROR: no github service connected';
  const p = String(path || '').replace(/^\/+/, '');
  if (!/^company\/agent-reports\/[A-Za-z0-9_.-]+\.md$/.test(p)) return 'ERROR: repo_commit only writes company/agent-reports/<name>.md - nothing else';
  const text = String(content || '').slice(0, 60000);
  if (!text.trim()) return 'ERROR: content is empty';
  const api = `https://api.github.com/repos/lordbasilaiassistant-sudo/broketobuilt/contents/${p}`;
  const hdrs = { [c.headerName || 'authorization']: c.headerValue || '', 'user-agent': 'StaffroomBot/1.0', accept: 'application/vnd.github+json' };
  try {
    let sha;
    const cur = await fetch(api, { headers: hdrs, signal: AbortSignal.timeout(20000) });
    if (cur.ok) sha = (await cur.json()).sha;
    const bytes = new TextEncoder().encode(text);
    let bin = '';
    for (let i = 0; i < bytes.length; i += 8192) bin += String.fromCharCode(...bytes.subarray(i, i + 8192));
    const r = await fetch(api, {
      method: 'PUT', headers: { ...hdrs, 'content-type': 'application/json' },
      body: JSON.stringify({ message: String(message || `office report: ${p}`).slice(0, 200), content: btoa(bin), ...(sha ? { sha } : {}) }),
      signal: AbortSignal.timeout(30000),
    });
    if (!r.ok) return `ERROR: GitHub HTTP ${r.status}: ${(await r.text()).slice(0, 200)}`;
    return `committed ${p} to the company repo`;
  } catch (e) { return `ERROR: ${String(e?.message || e).slice(0, 150)}`; }
}

/* Read a company-repo file (the repo is PRIVATE - raw URLs 404, so this is the only way a
 * staffer reads the books: HEALTH-STATUS, fleet-status, backlogs, prior reports). company/ only. */
async function repoRead(env, tp, path) {
  const { custom = [] } = await getConnectors(env, tp);
  const c = custom.find((x) => x.name.toLowerCase() === 'github');
  if (!c) return 'ERROR: no github service connected';
  const p0 = String(path || '').replace(/^\/+/, '');
  // path courtesy (2026-08-14): staffers passed "IDEAS_BACKLOG.md" bare, got a guard error, and
  // reported the file "missing" — auto-prefix instead of failing a read that was always in scope
  const p = p0.startsWith('company/') ? p0 : 'company/' + p0;
  if (!/^company\/[A-Za-z0-9_\/.-]+$/.test(p) || p.includes('..')) return 'ERROR: repo_read only reads company/... paths';
  try {
    const r = await fetch(`https://api.github.com/repos/lordbasilaiassistant-sudo/broketobuilt/contents/${p}`, {
      headers: { [c.headerName || 'authorization']: c.headerValue || '', 'user-agent': 'StaffroomBot/1.0', accept: 'application/vnd.github.raw' },
      signal: AbortSignal.timeout(20000),
    });
    if (!r.ok) return `ERROR: HTTP ${r.status} for ${p}`;
    return (await r.text()).slice(0, 12000);
  } catch (e) { return `ERROR: ${String(e?.message || e).slice(0, 150)}`; }
}

/* TOOL ROUTING (2026-08-14: flash-class brains collapse under 23 tools and start fabricating).
 * Each turn only carries the core tools + the ones the incoming text makes relevant. */
function pickTools(text) {
  const t = String(text || '').toLowerCase();
  // api_call + http_request live in the baseline (bench scar: an Auditor bounce carries no
  // 'api' keyword, so the retry round arrived tool-starved and could only apologize)
  const names = new Set(['fs_read', 'fs_list', 'fs_write', 'log_activity', 'list_team', 'message_teammate', 'ask_user', 'coworker_report', 'api_call', 'http_request']);
  const add = (...xs) => xs.forEach((x) => names.add(x));
  if (/mail|inbox|email/.test(t)) add('gmail_unread');
  if (/calendar|schedule|meeting|appointment|this week|today|tomorrow/.test(t)) add('calendar_read');
  if (/youtube|comment/.test(t)) add('yt_recent_comments', 'yt_reply');
  if (/wallet|balance|crypto|\beth\b|bankr|coin/.test(t)) add('wallet_list', 'wallet_create', 'wallet_import');
  if (/\brss\b|feed|news|headline/.test(t)) add('feed_read');
  if (/search|research|find|look ?up|price|pricing|competitor|compare/.test(t)) add('web_search', 'web_fetch', 'browser_visit');
  if (/browse|website|web ?page|\bvisit\b|screenshot|\burl\b|http/.test(t)) add('web_fetch', 'browser_visit');
  if (/log ?in|sign ?in|login.?desk|credential|connect .{0,15}account/.test(t)) add('login_desk', 'collect_login');
  if (/collected/.test(t)) add('collect_login');
  if (/notify|ping|alert|phone/.test(t)) add('notify_boss');
  if (/routine|daily|every |cron|recurring|standing order/.test(t)) add('set_routine');
  if (/hire|new (teammate|staffer|agent|employee)/.test(t)) add('hire_staffer');
  if (/\bapi\b|service|apify|github/.test(t)) add('api_call', 'http_request');
  if (/\bpost\b|\bput\b|endpoint|payload|webhook|http_request|submit .{0,12}(api|json|data)/.test(t)) add('http_request');
  if (/repo_commit|repo_read|agent-reports|company repo|commit .{0,20}report|health-status|fleet-status|ideas_backlog/i.test(t)) add('repo_commit', 'repo_read');
  if (/team_stats|review|scorecard|grade|performance/i.test(t)) add('team_stats', 'repo_commit', 'coworker_report');
  if (names.size <= 9) add('web_search', 'web_fetch'); // nothing matched: research basics
  return RUNNER_TOOLS.filter((x) => names.has(x.name));
}

/* OPENAI-FORMAT ADAPTER: lets Groq's stronger free models (gpt-oss-120b etc.) be staffer brains.
 * Detected by URL (/chat/completions or groq). Same tools, same loop, different wire shape. */
function toOpenAI(system, messages, tools) {
  const out = [{ role: 'system', content: system }];
  for (const m of messages) {
    if (typeof m.content === 'string') { out.push({ role: m.role, content: m.content }); continue; }
    if (m.role === 'assistant') {
      const text = m.content.filter((c) => c.type === 'text').map((c) => c.text).join('\n');
      const calls = m.content.filter((c) => c.type === 'tool_use').map((c) => ({ id: c.id, type: 'function', function: { name: c.name, arguments: JSON.stringify(c.input || {}) } }));
      out.push({ role: 'assistant', content: text || null, ...(calls.length ? { tool_calls: calls } : {}) });
    } else {
      const results = Array.isArray(m.content) ? m.content.filter((c) => c.type === 'tool_result') : [];
      if (results.length) for (const r of results) out.push({ role: 'tool', tool_call_id: r.tool_use_id, content: String(r.content).slice(0, 4000) });
      else out.push({ role: 'user', content: Array.isArray(m.content) ? m.content.map((c) => c.text || '').filter(Boolean).join('\n') : String(m.content) });
    }
  }
  return { messages: out, tools: tools.map((t) => ({ type: 'function', function: { name: t.name, description: t.description, parameters: t.input_schema } })) };
}
function fromOpenAI(d) {
  const ch = d.choices?.[0]?.message || {};
  const content = [];
  if (ch.content) content.push({ type: 'text', text: String(ch.content) });
  for (const tc of ch.tool_calls || []) {
    let input = {};
    try { input = JSON.parse(tc.function?.arguments || '{}'); } catch {}
    content.push({ type: 'tool_use', id: tc.id || 'tc_' + Math.floor(Date.now() % 1e7), name: tc.function?.name, input });
  }
  return { content };
}

function systemPrompt(staffer, officeCtx) {
  const deptLine = staffer.dept || staffer.spec ? `Department: ${staffer.dept || 'none'}. Your ONE specialization: ${staffer.spec || staffer.bio}. STAY NARROW - you do your specialization and nothing else; every other task gets routed to the teammate whose dept/specialization fits (list_team shows who's who). Having a tool that COULD try a task does not make it yours: before acting, ask "is this MY specialization?" - if not, message_teammate the right desk immediately instead of guessing at it yourself (bench scar: a YouTube staffer burned 4 API calls on a finance question that Finance answers in one).\n` : '';
  return `You are ${staffer.screen_name}, an AI staffer at a company. Your charge: ${staffer.bio}.
${deptLine}You are talking with your team in a private chat. The newest message is addressed to you.
${officeCtx || ''}

Rules:
- Be terse and concrete. You are a coworker, not an assistant: no "How can I help", no filler.
- PLAIN TEXT only - no markdown (**bold**, ##headers). Dashes for lists are fine. Speak directly
  to the sender; never restate their message or write meta-lines like "a new member joined".
- If the message is a work order naming files (shared/...), USE YOUR TOOLS: read the files, do the
  work, write results back, log_activity as you go. Only claim "done" if you actually wrote the fix.
- If you cannot complete something, say exactly what you did and what blocked you. Never bluff:
  every tool you run is recorded in a public ledger under your message, and claims that outrun
  your actions (saying "delegated"/"wrote"/"notified" without the tool call) get stamped as lies.
- If the message is a question or chat, just answer it well. No tools needed.
- You have a browser: web_search finds things online, web_fetch reads a page. Research runs through
  them, never from memory; save anything worth keeping with fs_write (your files are yours).
- Questions about the boss's mail, calendar, wallets, feeds or services MUST go through the tool
  (gmail_unread, calendar_read, wallet_list, feed_read, api_call). Answering from imagination is
  fabrication - the empty ledger under your reply exposes it and the Auditor bounces it back.
- Need an account you are not signed into? login_desk opens YOUR browser for the boss to sign in
  by hand (their password never touches chat), then collect_login saves it to YOUR jar - after
  that browser_visit is signed in there. Logins live on your computer only, never a teammate's.
- A decision that is genuinely the boss's (taste, budget, direction) → ask_user with 2-4 clickable
  options, never a guess and never an open question you could answer yourself. ONE question at a
  time, wizard-style, and every question must build on what the thread and connections already
  tell you - never ask what you can see.
- Boss wants a new teammate? Interview them with ask_user (role first, then name), then
  hire_staffer. Boss needs a connection that is not there? Name the exact Connectors-panel field
  and what to paste; keys go in the panel, never in chat.
- calendar_read and feed_read see the boss's connected calendar/feeds.
- Your own computer: personal drafts, tests and versions live under ${staffer.screen_name.toLowerCase()}/ .
  shared/ is the TEAM workspace - finished work gets committed there for everyone, always.
- Judge who to trust: coworker_report shows a teammate's recent work with verification verdicts.
  set_routine puts recurring work on a teammate's calendar - the team runs itself.
- Work a teammate sends you: do it, and your reply reaches them automatically. When a teammate
  REPORTS BACK to you, continue only if something still needs doing - a good report needs no reply.
- The boss HATES pings. notify_boss only if they explicitly asked to be told, or everything is
  blocked on them. ask_user already pings - never double up.
- You may call SEVERAL tools in one round - batch them (all your delegations at once, parallel
  reads at once). Tool rounds are scarce; one-at-a-time burns them.
- DELEGATING is cheap: list_team once, then ONE message_teammate per job - several jobs means
  several message_teammate calls, ALL IN THE SAME ROUND. Include a concrete shared/ file path in
  each order so the work is verifiable. Then reply saying who got what and why. Do not do a task
  yourself if you are delegating it.
- WORK ORIGINATES FROM THREE SOURCES ONLY: the boss (Anthony), your standing routine, or a
  Webhook event. You may decompose and delegate a task you were GIVEN; you may NEVER originate
  a new project, "improvement", or investigation on your own initiative - an office that invents
  its own work burns real money on phantoms. If you cannot trace the task in front of you to one
  of those three sources in this thread, say "unsourced task - parking it" and stop.
- PERMISSIONS ARE SIMPLE: every tool in your list is ALREADY authorized - connected services
  included, no extra consent step exists. There are NO department file permissions, NO upload
  permissions: every staffer reads and writes ALL of shared/. If you catch yourself typing
  "I don't have permission/access" - stop, you are hallucinating a barrier; RUN the tool and
  report its actual output or its actual error instead.
- Never say a tool "does not exist" from memory - your live tool list is in front of you every
  round. If a tool you expected is genuinely absent this round, say which task needs it and finish
  the rest; if a tool errors, quote the error verbatim.
- Task outside your charge? NEVER "I can't do that." The only acceptable answer is "I know who
  can" - list_team, pick the best fit, message_teammate them the job, and tell the sender who has
  it and why. Every task finds its owner; nothing bounces back unowned.
- Finish with your reply to the team (plain text). That final text is what gets posted, stamped
  with your name - NEVER prefix it with "${staffer.screen_name}:".`;
}

/* The staff's browser + search (2026-08-14, Anthony: "they need to check online for things and
 * download what they need"). Search = Tavily (our free 1000/mo key); fetch = plain GET with the
 * HTML stripped and a hard cap so one page can't blow the context. */
async function webSearch(env, query) {
  if (!query) return 'ERROR: query is required';
  if (!env.TAVILY_API_KEY) return 'ERROR: search is not configured on this computer yet';
  const r = await fetch('https://api.tavily.com/search', {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ api_key: env.TAVILY_API_KEY, query: query.slice(0, 300), max_results: 5 }),
    signal: AbortSignal.timeout(20000),
  });
  if (!r.ok) return `ERROR: search HTTP ${r.status}`;
  const d = await r.json();
  return (d.results || []).map((x) => `${x.title}\n${x.url}\n${String(x.content || '').slice(0, 300)}`).join('\n\n') || 'no results';
}
/* Arbitrary-URL HTTP (2026-08-15, "anything we throw at them" bench): web_fetch is GET-only and
 * api_call needs a connector, so a plain "POST to this public API" order was structurally
 * impossible. No connector auth is ever attached here - secrets stay in api_call's lane. */
async function httpRequest(url, method, body, headers) {
  if (!/^https?:\/\//i.test(String(url || ''))) return 'ERROR: url must start with http(s)://';
  const m = String(method || 'GET').toUpperCase();
  if (!['GET', 'POST', 'PUT', 'DELETE'].includes(m)) return 'ERROR: method must be GET/POST/PUT/DELETE';
  const h = { 'user-agent': 'StaffroomBot/1.0 (+https://broke2builtai.com)' };
  for (const [k, v] of Object.entries(headers || {})) {
    if (/^(authorization|cookie|x-api-key)$/i.test(k)) return `ERROR: never send credentials via http_request - auth belongs to api_call connectors`;
    h[String(k).slice(0, 60)] = String(v).slice(0, 500);
  }
  if (body && !h['content-type']) h['content-type'] = 'application/json';
  try {
    const r = await fetch(url, { method: m, headers: h, body: body ? String(body).slice(0, 16000) : undefined, signal: AbortSignal.timeout(25000), redirect: 'follow' });
    return `HTTP ${r.status}\n${(await r.text()).slice(0, 8000)}`;
  } catch (e) { return `ERROR: ${String(e?.message || e).slice(0, 150)}`; }
}
async function webFetch(url) {
  if (!/^https?:\/\//i.test(url)) return 'ERROR: url must start with http(s)://';
  let r;
  try {
    r = await fetch(url, { headers: { 'user-agent': 'StaffroomBot/1.0 (+https://broke2builtai.com)' }, signal: AbortSignal.timeout(20000), redirect: 'follow' });
  } catch (e) { return `ERROR: fetch failed - ${String(e?.message || e).slice(0, 120)}`; }
  if (!r.ok) return `ERROR: HTTP ${r.status} from ${url}`;
  const raw = (await r.text()).slice(0, 400000);
  const text = raw
    .replace(/<script[\s\S]*?<\/script>/gi, ' ').replace(/<style[\s\S]*?<\/style>/gi, ' ')
    .replace(/<[^>]+>/g, ' ').replace(/&nbsp;/g, ' ').replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
    .replace(/\s{3,}/g, '\n').trim();
  return text.slice(0, 8000) || '(page had no readable text)';
}

/* ── GOOGLE (one-click connect, 2026-08-14): per-account refresh token at system/google/<acct>.json
 * (root namespace - staffer fs tools can't read it). Tools get short-lived access tokens on
 * demand. Read-only scopes only; sending mail is a later, human-gated build. */
export async function googleToken(env, tp) {
  const o = await env.FS.get(`system/google/${acctOf(tp)}.json`);
  if (!o) return null;
  const g = JSON.parse(await o.text());
  if (!g.refresh_token) return null;
  const r = await fetch('https://oauth2.googleapis.com/token', {
    method: 'POST',
    headers: { 'content-type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({ client_id: env.GOOGLE_OAUTH_CLIENT_ID, client_secret: env.GOOGLE_OAUTH_CLIENT_SECRET, refresh_token: g.refresh_token, grant_type: 'refresh_token' }),
    signal: AbortSignal.timeout(15000),
  });
  const d = await r.json().catch(() => ({}));
  return d.access_token || null;
}
async function gmailUnread(env, tp, limit) {
  const at = await googleToken(env, tp);
  if (!at) return 'Google is not connected - the boss can click "Connect Google" in the Connectors panel';
  const h = { authorization: `Bearer ${at}` };
  const list = await (await fetch(`https://gmail.googleapis.com/gmail/v1/users/me/messages?q=is:unread&maxResults=${Math.min(limit || 8, 15)}`, { headers: h, signal: AbortSignal.timeout(20000) })).json();
  if (!list.messages?.length) return 'no unread mail';
  const out = [];
  for (const m of list.messages) {
    const d = await (await fetch(`https://gmail.googleapis.com/gmail/v1/users/me/messages/${m.id}?format=metadata&metadataHeaders=From&metadataHeaders=Subject&metadataHeaders=Date`, { headers: h, signal: AbortSignal.timeout(20000) })).json();
    const hd = Object.fromEntries((d.payload?.headers || []).map((x) => [x.name, x.value]));
    out.push(`${hd.Date || ''} | ${hd.From || '?'} | ${hd.Subject || '(no subject)'}\n  ${String(d.snippet || '').slice(0, 160)}`);
  }
  return out.join('\n');
}
async function ytRecentComments(env, tp, limit) {
  const at = await googleToken(env, tp);
  if (!at) return 'Google is not connected - the boss can click Connect Google in the panel (YouTube needs a reconnect after the scope update)';
  const h = { authorization: `Bearer ${at}` };
  const ch = await (await fetch('https://www.googleapis.com/youtube/v3/channels?part=id&mine=true', { headers: h, signal: AbortSignal.timeout(20000) })).json();
  const chId = ch.items?.[0]?.id;
  if (!chId) return `ERROR: could not resolve the channel${ch.error ? ' - ' + String(ch.error.message).slice(0, 120) : ''} (reconnect Google to grant YouTube access)`;
  const d = await (await fetch(`https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&allThreadsRelatedToChannelId=${chId}&order=time&maxResults=${Math.min(limit || 15, 30)}&textFormat=plainText`, { headers: h, signal: AbortSignal.timeout(20000) })).json();
  if (!Array.isArray(d.items)) return `ERROR: ${String(d.error?.message || 'comment list failed').slice(0, 150)}`;
  if (!d.items.length) return 'no comments yet';
  // replied-ledger (2026-08-14, Tuber re-reply scar): the model cannot tell OUR reply from anyone
  // else's in totalReplyCount, so an every-3h routine happily answers the same comment forever.
  // Answered threads are filtered OUT here — what the model can't see it can't re-reply to.
  const seenO = await env.FS.get(`${tp}system/yt-replied.json`);
  const seen = new Set(seenO ? JSON.parse(await seenO.text()) : []);
  const fresh = d.items.filter((t) => !seen.has(t.snippet?.topLevelComment?.id));
  const skipped = d.items.length - fresh.length;
  if (!fresh.length) return `no new comments - all ${skipped} recent threads already answered by us earlier`;
  return (skipped ? `(${skipped} older threads hidden - already answered by us)\n` : '') + fresh.map((t) => {
    const c = t.snippet?.topLevelComment?.snippet || {};
    return `[${t.snippet?.topLevelComment?.id}] ${c.authorDisplayName} on video ${c.videoId} (${(c.publishedAt || '').slice(0, 16)}): ${String(c.textDisplay || '').slice(0, 200)} (${t.snippet?.totalReplyCount || 0} replies)`;
  }).join('\n');
}
async function ytReply(env, tp, parentId, text) {
  const at = await googleToken(env, tp);
  if (!at) return 'Google is not connected';
  if (!parentId || !text) return 'ERROR: need parent_id and text';
  const r = await fetch('https://www.googleapis.com/youtube/v3/comments?part=snippet', {
    method: 'POST',
    headers: { authorization: `Bearer ${at}`, 'content-type': 'application/json' },
    body: JSON.stringify({ snippet: { parentId, textOriginal: String(text).slice(0, 1000) } }),
    signal: AbortSignal.timeout(20000),
  });
  const d = await r.json().catch(() => ({}));
  if (r.ok) {
    // record the answered thread so ytRecentComments never shows it again (re-reply scar)
    const k = `${tp}system/yt-replied.json`;
    const o = await env.FS.get(k);
    const seen = o ? JSON.parse(await o.text()) : [];
    if (!seen.includes(parentId)) { seen.push(parentId); await env.FS.put(k, JSON.stringify(seen.slice(-500))); }
  }
  return r.ok ? `replied to ${parentId}` : `ERROR: ${String(d.error?.message || 'reply failed').slice(0, 150)}`;
}

async function gcalEvents(env, tp, days) {
  const at = await googleToken(env, tp);
  if (!at) return null; // caller falls back to ICS
  const now = new Date().toISOString();
  const max = new Date(Date.now() + (days > 0 && days <= 60 ? days : 7) * 86400000).toISOString();
  const d = await (await fetch(`https://www.googleapis.com/calendar/v3/calendars/primary/events?timeMin=${encodeURIComponent(now)}&timeMax=${encodeURIComponent(max)}&singleEvents=true&orderBy=startTime&maxResults=20`, { headers: { authorization: `Bearer ${at}` }, signal: AbortSignal.timeout(20000) })).json();
  if (!Array.isArray(d.items)) return null;
  if (!d.items.length) return 'no events in that window';
  return d.items.map((e) => `${(e.start?.dateTime || e.start?.date || '').slice(0, 16).replace('T', ' ')} - ${String(e.summary || '(untitled)').slice(0, 120)}${e.location ? ' @ ' + String(e.location).slice(0, 60) : ''}`).join('\n');
}

/* ── LOGIN DESK (Anthony 2026-08-14: "the human can log in on THAT staffer's PC, not any other
 * agent's"). Flow: staffer opens a real Browser Run session (10 min) → boss gets the Live View
 * URL and signs in by hand → staffer collects the cookies into ITS OWN jar (per staffer, per
 * account, root-namespace) → later browser_visit calls ride those cookies = logged-in browsing. */
const jarKey = (tp, who) => `system/cookies/${acctOf(tp)}-${who}.json`;
const deskKey = (tp, who) => `system/browser-login/${acctOf(tp)}-${who}.json`;
async function loginDesk(env, tp, who, service) {
  if (!env.CF_BR_TOKEN) return 'ERROR: the office Chrome is not configured';
  const r = await fetch(`https://api.cloudflare.com/client/v4/accounts/${CF_ACC}/browser-rendering/devtools/browser?keep_alive=600000&targets=true`, {
    method: 'POST', headers: { authorization: `Bearer ${env.CF_BR_TOKEN}` }, signal: AbortSignal.timeout(30000),
  });
  const d = await r.json().catch(() => ({}));
  const view = d.targets?.[0]?.devtoolsFrontendUrl;
  if (!d.sessionId || !view) return `ERROR: could not open a desk (${JSON.stringify(d).slice(0, 120)})`;
  await env.FS.put(deskKey(tp, who), JSON.stringify({ sessionId: d.sessionId, ws: d.webSocketDebuggerUrl, created: new Date().toISOString() }));
  return `My login desk is OPEN for 10 minutes. Boss: open this link, type ${service || 'the site'} in the address bar, sign in as yourself, then tell me "collected" so I run collect_login:\n${view}\n(The link expires after ~5 minutes of not being opened - ask me to reopen if it dies.)`;
}
async function collectLogin(env, tp, who) {
  const o = await env.FS.get(deskKey(tp, who));
  if (!o) return 'ERROR: no open login desk - use login_desk first';
  const desk = JSON.parse(await o.text());
  let cookies = [];
  try {
    const httpsUrl = String(desk.ws).replace(/^wss:/, 'https:');
    const resp = await fetch(httpsUrl, { headers: { Upgrade: 'websocket', authorization: `Bearer ${env.CF_BR_TOKEN}` } });
    const ws = resp.webSocket;
    if (!ws) return 'ERROR: could not attach to the desk (session may have expired)';
    ws.accept();
    cookies = await new Promise((resolve, reject) => {
      const timer = setTimeout(() => reject(new Error('cdp timeout')), 12000);
      ws.addEventListener('message', (ev) => {
        try {
          const m = JSON.parse(ev.data);
          if (m.id === 1) { clearTimeout(timer); resolve(m.result?.cookies || []); }
        } catch {}
      });
      ws.send(JSON.stringify({ id: 1, method: 'Storage.getCookies', params: {} }));
    });
    ws.close();
  } catch (e) { return `ERROR: cookie collection failed - ${String(e?.message || e).slice(0, 120)}`; }
  if (!cookies.length) return 'the desk had no cookies yet - did the sign-in finish? Keep the desk open and try again';
  const prevO = await env.FS.get(jarKey(tp, who));
  const jar = prevO ? JSON.parse(await prevO.text()) : [];
  const seen = new Set(jar.map((c) => c.name + '|' + c.domain));
  for (const c of cookies) {
    const k = c.name + '|' + c.domain;
    if (seen.has(k)) { const i = jar.findIndex((x) => x.name === c.name && x.domain === c.domain); jar[i] = c; }
    else jar.push(c);
  }
  await env.FS.put(jarKey(tp, who), JSON.stringify(jar.slice(-120)));
  await env.FS.delete(deskKey(tp, who));
  const domains = [...new Set(cookies.map((c) => c.domain))].slice(0, 8).join(', ');
  return `collected ${cookies.length} cookies into MY jar (domains: ${domains}). My browser is now signed in there - browser_visit uses them automatically. Keys never appear in chat.`;
}

/* browser_visit — each staffer's own Chrome, via Cloudflare Browser Run (MEASURED 2026-08-14:
 * Workers Paid includes 10 browser-hours/mo + 120 concurrent; REST quick-actions bill duration
 * only). The model's eyes are the MARKDOWN (no vision model needed); the screenshot is for the
 * human's monitor pane. Frugal by design: one markdown + one screenshot call per visit. */
const CF_ACC = '74fd6fc5698b1be17be82628ee6f2eaf';
async function browserVisit(env, who, tp, url) {
  if (!/^https?:\/\//i.test(url)) return 'ERROR: url must start with http(s)://';
  if (!env.CF_BR_TOKEN) return 'ERROR: the office Chrome is not configured yet';
  const hdrs = { authorization: `Bearer ${env.CF_BR_TOKEN}`, 'content-type': 'application/json' };
  const base = `https://api.cloudflare.com/client/v4/accounts/${CF_ACC}/browser-rendering`;
  // the staffer's own cookie jar rides along: logged-in browsing after a login-desk handoff
  let cookies;
  try {
    const j = await env.FS.get(jarKey(tp, who));
    if (j) cookies = JSON.parse(await j.text()).map((c) => ({ name: c.name, value: c.value, domain: c.domain, path: c.path || '/' }));
  } catch {}
  const withJar = (body) => JSON.stringify(cookies?.length ? { ...body, cookies } : body);
  let md = '';
  try {
    const r = await fetch(`${base}/markdown`, { method: 'POST', headers: hdrs, body: withJar({ url }), signal: AbortSignal.timeout(45000) });
    const d = await r.json().catch(() => ({}));
    if (!d.success) return `ERROR: browser could not open ${url} (${JSON.stringify(d.errors || d).slice(0, 150)})`;
    md = String(d.result || '').slice(0, 8000);
  } catch (e) { return `ERROR: browser failed - ${String(e?.message || e).slice(0, 120)}`; }
  // the monitor frame: best-effort, never blocks the read
  try {
    const s = await fetch(`${base}/screenshot`, { method: 'POST', headers: hdrs, body: withJar({ url, screenshotOptions: { type: 'png' }, viewport: { width: 1280, height: 800 } }), signal: AbortSignal.timeout(45000) });
    if (s.ok && (s.headers.get('content-type') || '').includes('image')) {
      const bytes = new Uint8Array(await s.arrayBuffer());
      if (bytes.length <= 4 * 1024 * 1024) await env.FS.put(`${tp}screens/${who}/latest.png`, bytes, { contentType: 'image/png' });
    }
  } catch {}
  return md || '(page had no readable text)';
}

async function callBrain(env, system, messages, brain, opts) {
  // BYOM: a staffer may carry its own endpoint/model/key (Anthropic- or OpenAI-format)
  const url = brain?.url || ZAI;
  const model = brain?.model || MODEL;
  const key = brain?.key || (/groq\.com/.test(url) ? env.GROQ_API_KEY : env.ZAI_API_KEY);
  const toolList = opts?.tools === false ? [] : (opts?.toolList || RUNNER_TOOLS);
  const isOpenAI = /\/chat\/completions|groq\.com/.test(url);
  if (isOpenAI) {
    const conv = toOpenAI(system, messages, toolList);
    const body = { model, max_tokens: opts?.maxTokens || 1200, messages: conv.messages };
    if (toolList.length) { body.tools = conv.tools; body.tool_choice = 'auto'; }
    // free tiers rate-limit per MINUTE (Groq gpt-oss = 8000 TPM): a multi-round loop always
    // trips it, so a 429 waits out the window once instead of killing the whole turn
    for (let attempt = 0; ; attempt++) {
      const r = await fetch(url, {
        method: 'POST',
        headers: { 'content-type': 'application/json', authorization: `Bearer ${key}` },
        body: JSON.stringify(body),
        signal: AbortSignal.timeout(90000),
      });
      if (r.status === 429 && attempt < 2) {
        const hdr = Number(r.headers.get('retry-after'));
        const m = (await r.text()).match(/try again in ([\d.]+)s/i);
        const waitS = Math.min(65, (hdr > 0 ? hdr : m ? Number(m[1]) : 20) + 1);
        await new Promise((res) => setTimeout(res, waitS * 1000));
        continue;
      }
      if (!r.ok) throw new Error(`brain HTTP ${r.status}: ${(await r.text()).slice(0, 200)}`);
      return fromOpenAI(await r.json());
    }
  }
  const body = { model, max_tokens: opts?.maxTokens || 1200, system, messages };
  if (toolList.length) body.tools = toolList;
  const r = await fetch(url, {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      'x-api-key': key,
      'authorization': `Bearer ${key}`,
      'anthropic-version': '2023-06-01',
    },
    body: JSON.stringify(body),
    signal: AbortSignal.timeout(90000),
  });
  if (!r.ok) throw new Error(`brain HTTP ${r.status}: ${(await r.text()).slice(0, 200)}`);
  return r.json();
}

/* ── THE AUDITOR (2026-08-14, Anthony: "a reflection ai checking every claim, silently") ─────────
 * Not a staffer - no desk, no thread, no voice. Every few minutes it takes recent staffer replies
 * that lack an audit stamp, gathers EVIDENCE (the order, the action ledger, the actual heads of
 * any shared/ files named), and judges whether the reply's claims hold. Verdict lands as a quiet
 * 🛡 stamp on the message. It only ever judges with artifacts in hand - never vibes. */
const AUDIT_SYS = `You are the office Auditor. Your only job: does this staffer's reply tell the truth?
You get: the work order, the reply, a LEDGER of tools the staffer actually ran (ground truth - the
harness recorded it), and the current content of any files involved. Judge ONLY what the reply
claims: work claimed done must be evidenced by the ledger and file contents; numbers quoted must
appear in the evidence; delegation claimed must show message_teammate in the ledger. Chat or
questions with no claims = ok. The LEDGER IS AUTHORITATIVE - never contradict it. An honest
report of being BLOCKED or failing, with the ledger showing real attempts, is ok (honesty is the
point); only stamp false when a claim of SUCCESS lacks evidence. A reply presenting SPECIFIC DATA
(mail counts, senders, calendar events, balances, numbers) while the ledger is EMPTY is fabricated
- stamp it false.
Second check, ROUTING (the office law is narrow specialization): if the reply ATTEMPTS or ANSWERS
work clearly outside the staffer's stated specialization instead of routing it to the right desk
via message_teammate, or if it asks THE BOSS to go do the legwork (check a dashboard, look
something up) when a TEAMMATE owns that lane, stamp it false with reason "route it: <task> belongs
to <dept> - message_teammate them". Honest in-lane blockers stay ok.
Reply with STRICT JSON only, nothing else: {"ok":true|false,"reason":"<=80 chars"}`;
export async function auditTick(env, tp = '', deps) {
  const threads = await env.FS.list({ prefix: `${tp}threads/`, limit: 30 });
  let budget = 4;
  for (const t of threads.objects) {
    if (budget <= 0) break;
    const obj = await env.FS.get(t.key);
    if (!obj) continue;
    const lines = (await obj.text()).split('\n').filter(Boolean);
    const msgs = lines.map((l) => JSON.parse(l));
    const owner = t.key.slice(`${tp}threads/`.length).replace(/\.jsonl$/, '').toLowerCase();
    for (let i = Math.max(0, msgs.length - 5); i < msgs.length && budget > 0; i++) {
      const m = msgs[i];
      if (!Array.isArray(m.actions) || m.audit || m.options) continue; // runner replies only, once
      // only the thread owner's own replies: round-trip report copies from teammates carry a
      // ledger too, and auditing them HERE bounces the wrong staffer against the wrong order
      if (m.report || String(m.from).toLowerCase() !== owner) continue;
      budget--;
      const order = [...msgs.slice(0, i)].reverse().find((x) => x.from !== m.from);
      const paths = [...new Set(`${order?.body || ''}\n${m.body}`.match(/shared\/[\w\/.-]+\.\w+/g) || [])].slice(0, 3);
      let evidence = '';
      for (const p of paths) {
        const f = await env.FS.get(tp + p);
        evidence += `\n--- ${p} ${f ? '(exists)' : '(DOES NOT EXIST)'} ---\n${f ? (await f.text()).slice(0, 600) : ''}`;
      }
      // routing check needs to know who does what (bench scar: out-of-lane grabs + boss-punts)
      const me = deps?.staff?.find((s) => s.screen_name.toLowerCase() === owner);
      const rosterLine = (deps?.staff || []).map((s) => `${s.screen_name} (${s.dept || '-'}: ${String(s.spec || s.bio || '').slice(0, 45)})`).join(' · ');
      const prompt = `THIS STAFFER'S SPECIALIZATION: ${me ? `${me.dept || '-'} - ${me.spec || me.bio}` : 'unknown'}\nTHE TEAM: ${rosterLine || 'unknown'}\n\nWORK ORDER (${order?.from || 'none'}): ${(order?.body || '(no prior order)').slice(0, 800)}\n\nSTAFFER REPLY (${m.from}): ${m.body.slice(0, 800)}\n\nLEDGER (tools actually run): ${m.actions.join(', ') || 'none'}\n\nFILE EVIDENCE:${evidence || ' (no files named)'}`;
      try {
        const res = await callBrain(env, AUDIT_SYS, [{ role: 'user', content: prompt }], null, { tools: false, maxTokens: 150 });
        const text = (res.content || []).filter((c) => c.type === 'text').map((c) => c.text).join('');
        const j = JSON.parse((text.match(/\{[\s\S]*\}/) || ['{}'])[0]);
        if (typeof j.ok !== 'boolean') continue; // schema gate: no verdict, no stamp
        m.audit = { v: j.ok ? 'ok' : 'suspect', reason: String(j.reason || '').slice(0, 80), t: new Date().toISOString() };
      } catch { continue; }
    }
    // re-read before write to shrink the append race window, then patch our stamps in
    const fresh = await env.FS.get(t.key);
    if (!fresh) continue;
    const freshLines = (await fresh.text()).split('\n').filter(Boolean);
    const freshMsgs = freshLines.map((l) => JSON.parse(l));
    let changed = false;
    for (const fm of freshMsgs) {
      const src = msgs.find((x) => x.created_at === fm.created_at && x.from === fm.from);
      if (src?.audit && !fm.audit) { fm.audit = src.audit; changed = true; }
    }
    if (changed) await env.FS.put(t.key, freshMsgs.map((x) => JSON.stringify(x)).join('\n') + '\n');
    // suspect stamp on the thread's LIVE tail = a work order: bounce it back for one retry.
    // BOUNCE CAP (2026-08-15 churn scar): an office-Eli-invented phantom project ping-ponged
    // through bounces for hours - each weak retry earned a fresh stamp and a fresh bounce.
    // Max 2 Auditor bounces without an intervening human message; then park it, once, quietly.
    const tail = freshMsgs[freshMsgs.length - 1];
    const sinceHuman = [];
    for (let k = freshMsgs.length - 1; k >= 0; k--) { if (freshMsgs[k].from === 'Anthony') break; sinceHuman.push(freshMsgs[k]); }
    const recentBounces = sinceHuman.filter((x) => x.from === 'Auditor').length;
    if (deps && changed && tail?.audit?.v === 'suspect' && recentBounces >= 2) {
      if (!sinceHuman.some((x) => x.from === 'Auditor' && /PARKED/.test(x.body))) {
        await deps.appendToThread(env, t.key.slice(`${tp}threads/`.length).replace(/\.jsonl$/, ''), 'Auditor', 'PARKED: two audit bounces did not produce verified work. This task is parked for the boss - no further attempts, no more replies about it. Take your next real order.');
      }
      continue;
    }
    if (deps && changed && tail?.audit?.v === 'suspect' && !tail.audit.retried) {
      tail.audit.retried = true;
      await env.FS.put(t.key, freshMsgs.map((x) => JSON.stringify(x)).join('\n') + '\n');
      const stafferName = tail.from;
      const st = deps.staff.find((s) => s.screen_name === stafferName);
      if (st) {
        const who2 = t.key.slice(`${tp}threads/`.length).replace(/\.jsonl$/, '');
        await deps.appendToThread(env, who2, 'Auditor', `Audit finding on your last reply: ${tail.audit.reason}. Redo it properly - run the tools, land the artifacts, then report honestly (or say exactly what blocks you).`);
        const st2 = st.brain?.model === STRONG_FALLBACK.model ? st : { ...st, brain: { ...STRONG_FALLBACK } };
        await respondForStaffer(env, { ...deps, retried: true, pending: [] }, st2).catch(() => {});
      }
    }
  }
}

/* Connectors live ROOT-side at system/connectors/<root|tid>.json — staffer fs tools can't read
 * them; only these purpose-built tools touch them. */
async function getConnectors(env, tp) {
  const id = tp ? (tp.match(/^tenants\/([a-f0-9]+)\//) || [])[1] : 'root';
  if (!id) return {};
  const o = await env.FS.get(`system/connectors/${id}.json`);
  return o ? JSON.parse(await o.text()) : {};
}
async function ntfyPush(topic, title, message) {
  if (!topic) return 'not configured - ask the boss to set an ntfy topic in Connectors';
  const r = await fetch(`https://ntfy.sh/${encodeURIComponent(topic)}`, {
    method: 'POST', headers: { title: String(title).slice(0, 80) }, body: String(message).slice(0, 1000),
    signal: AbortSignal.timeout(15000),
  });
  return r.ok ? 'pushed to the boss' : `push failed (HTTP ${r.status})`;
}
function parseIcsDate(v) {
  const m = String(v).match(/(\d{4})(\d{2})(\d{2})(?:T(\d{2})(\d{2})(\d{2})?(Z)?)?/);
  if (!m) return null;
  return new Date(Date.UTC(+m[1], +m[2] - 1, +m[3], +(m[4] || 0), +(m[5] || 0), +(m[6] || 0)));
}
async function calendarRead(env, tp, days) {
  const { ics_url } = await getConnectors(env, tp);
  if (!ics_url) return 'no calendar connected - the boss can paste their secret iCal/ICS link in the Connectors panel';
  let text;
  try { text = await (await fetch(ics_url, { signal: AbortSignal.timeout(20000) })).text(); }
  catch (e) { return `ERROR: calendar fetch failed - ${String(e?.message || e).slice(0, 100)}`; }
  const unfolded = text.replace(/\r?\n[ \t]/g, '');
  const now = Date.now(), until = now + (days > 0 && days <= 60 ? days : 7) * 86400000;
  const events = [];
  for (const block of unfolded.split('BEGIN:VEVENT').slice(1)) {
    const f = (name) => (block.match(new RegExp(`^${name}[^:]*:(.*)$`, 'm')) || [])[1] || '';
    const start = parseIcsDate(f('DTSTART'));
    if (!start || start.getTime() < now - 86400000 || start.getTime() > until) continue;
    events.push({ t: start.getTime(), line: `${start.toISOString().slice(0, 16).replace('T', ' ')} UTC - ${f('SUMMARY').slice(0, 120)}${f('LOCATION') ? ' @ ' + f('LOCATION').slice(0, 60) : ''}` });
  }
  events.sort((a, b) => a.t - b.t);
  return events.length ? events.slice(0, 20).map((e) => e.line).join('\n') : 'no events in that window';
}
async function feedRead(env, tp, urlArg) {
  const url = urlArg || (await getConnectors(env, tp)).rss_url;
  if (!url) return 'no feed connected and no url given - the boss can set a default feed in Connectors, or pass me a url';
  let text;
  try { text = await (await fetch(url, { headers: { 'user-agent': 'StaffroomBot/1.0' }, signal: AbortSignal.timeout(20000) })).text(); }
  catch (e) { return `ERROR: feed fetch failed - ${String(e?.message || e).slice(0, 100)}`; }
  const items = [...text.matchAll(/<(?:item|entry)[\s>][\s\S]*?<\/(?:item|entry)>/gi)].slice(0, 8).map((m) => {
    const b = m[0];
    const title = ((b.match(/<title[^>]*>(?:<!\[CDATA\[)?([\s\S]*?)(?:\]\]>)?<\/title>/i) || [])[1] || '').trim().slice(0, 140);
    const link = ((b.match(/<link[^>]*href="([^"]+)"/i) || b.match(/<link[^>]*>([^<]+)<\/link>/i) || [])[1] || '').trim();
    return `${title}\n${link}`;
  });
  return items.length ? items.join('\n\n') : 'feed had no readable items';
}

/* One staffer answers their thread. deps = { runTool, postActivity, appendToThread, staff } */
export async function respondForStaffer(env, deps, staffer) {
  const who = staffer.screen_name.toLowerCase();
  const tp = deps.tp || ''; // tenant prefix: '' = the company's root office
  const obj = await env.FS.get(`${tp}threads/${who}.jsonl`);
  if (!obj) return null;
  const msgs = (await obj.text()).split('\n').filter(Boolean).map((l) => JSON.parse(l));
  if (!msgs.length) return null;
  const last = msgs[msgs.length - 1];
  if (last.from === staffer.screen_name) return null; // already answered
  if (last.from !== 'Anthony' && !last.body) return null;

  // double-reply lock: wake-on-send and the cron can race. First writer wins for ~2 minutes.
  const lockKey = `${tp}system-status/${who}`;
  const lock = await env.FS.get(lockKey);
  if (lock && Date.now() - Number(await lock.text()) < 120000) return null;
  await env.FS.put(lockKey, String(Date.now())); // doubles as the "working" indicator the UI shows
  try {

  // thread tail as alternating turns (their messages = user, staffer's own = assistant)
  const tail = msgs.slice(-12).map((m) => ({
    role: m.from === staffer.screen_name ? 'assistant' : 'user',
    content: `${m.from}: ${m.body}`.slice(0, 2000),
  }));
  // Anthropic API requires first message role=user; drop leading assistant turns
  while (tail.length && tail[0].role === 'assistant') tail.shift();
  if (!tail.length) return null;

  const convo = [...tail];
  let finalText = null;
  let asked = false;
  const actionsLog = []; // the truth ledger: every tool that actually ran this turn
  // ambient office context: every staffer knows what the boss has connected, always
  let officeCtx = '';
  try {
    const c = await getConnectors(env, tp);
    const goog = await env.FS.get(`system/google/${acctOf(tp)}.json`);
    const parts = [goog && 'Google (gmail_unread + calendar)', c.ics_url && 'calendar ICS', c.rss_url && 'news feed', c.ntfy_topic && 'phone pings', c.bankr_api_key && 'Bankr wallet', ...(c.custom || []).map((x) => `service "${x.name}"`)].filter(Boolean);
    officeCtx = `Connected for this office: ${parts.length ? parts.join(', ') : 'nothing yet - the boss can add connectors in the panel'}.`;
  } catch {}
  // window of 4: an Auditor bounce carries no tool keywords - the ORIGINAL order two messages
  // back must still route tools, or the retry is tool-starved and can only confess (Eli scar)
  const toolList = pickTools(tail.slice(-4).map((m) => m.content).join(' '));
  for (let round = 0; round < MAX_ROUNDS; round++) {
    const res = await callBrain(env, systemPrompt(staffer, officeCtx), convo, staffer.brain, { toolList });
    const toolUses = (res.content || []).filter((c) => c.type === 'tool_use');
    const texts = (res.content || []).filter((c) => c.type === 'text').map((c) => c.text).join('\n').trim();
    if (!toolUses.length) { finalText = texts || null; break; }
    convo.push({ role: 'assistant', content: res.content });
    const results = [];
    for (const tu of toolUses) {
      let out;
      try {
        if (tu.name === 'log_activity') out = await deps.postActivity(env, { employee: who, action: tu.input?.action, detail: tu.input?.detail });
        else if (tu.name === 'web_search') out = await webSearch(env, String(tu.input?.query || ''));
        else if (tu.name === 'web_fetch') {
          const wurl = String(tu.input?.url || '');
          out = await webFetch(wurl);
          // same-zone loop: a worker fetching a sibling *.workers.dev URL gets routed back into
          // ITSELF and answers its own 404 - go out through the CF browser instead
          if (String(out).startsWith('ERROR') && /\.workers\.dev\//.test(wurl + '/')) out = await browserVisit(env, who, tp, wurl);
        }
        else if (tu.name === 'login_desk') out = await loginDesk(env, tp, who, String(tu.input?.service || ''));
        else if (tu.name === 'collect_login') out = await collectLogin(env, tp, who);
        else if (tu.name === 'browser_visit') {
          out = await browserVisit(env, who, tp, String(tu.input?.url || ''));
          if (!String(out).startsWith('ERROR')) await deps.postActivity(env, { employee: who, action: `Browsing ${String(tu.input?.url || '').slice(0, 80)}`, detail: 'opened in my Chrome - frame on my monitor' }).catch(() => {});
        }
        else if (tu.name === 'list_team') out = JSON.stringify(deps.staff.map((s) => ({ name: s.screen_name, dept: s.dept || '', specialization: s.spec || '', charge: s.bio })));
        else if (tu.name === 'message_teammate') {
          const target = deps.staff.find((s) => s.screen_name.toLowerCase() === String(tu.input?.to || '').toLowerCase());
          if (!target) out = `ERROR: no teammate named "${tu.input?.to}" - use list_team`;
          else if (target.screen_name === staffer.screen_name) out = 'ERROR: that is you';
          else {
            // dedupe: a bounced retry must not re-send the same order (duplicate work + thread noise)
            const orderBody = String(tu.input?.body || '').slice(0, 4000);
            const tThread = await env.FS.get(`${tp}threads/${target.screen_name.toLowerCase()}.jsonl`);
            const recent = tThread ? (await tThread.text()).split('\n').filter(Boolean).slice(-5).map((l) => JSON.parse(l)) : [];
            const dupe = recent.find((m) => m.from === staffer.screen_name && Date.now() - new Date(m.created_at) < 600000 && m.body.slice(0, 80) === orderBody.slice(0, 80));
            if (dupe) { out = `already delivered to ${target.screen_name} minutes ago - do not re-send; check back with coworker_report instead`; results.push({ type: 'tool_result', tool_use_id: tu.id, content: out }); continue; }
            await deps.appendToThread(env, target.screen_name.toLowerCase(), staffer.screen_name, orderBody);
            // instant delegation: wake the receiver now (ONE hop - a woken staffer can't wake others)
            if (deps.pending && !deps.oneHop) {
              deps.pending.push(respondForStaffer(env, { ...deps, pending: [], oneHop: true }, target).catch(() => {}));
            }
            out = `delivered to ${target.screen_name} - they are picking it up now; check back or ask them for the report`;
          }
        }
        else if (tu.name === 'ask_user') {
          const opts = (Array.isArray(tu.input?.options) ? tu.input.options : []).map((o) => String(o).slice(0, 60)).filter(Boolean).slice(0, 4);
          const q = String(tu.input?.question || '').slice(0, 1000);
          if (!q || opts.length < 2) out = 'ERROR: ask_user needs a question and 2-4 options';
          else {
            await deps.appendToThread(env, who, staffer.screen_name, q, opts, actionsLog.slice());
            try { const c = await getConnectors(env, tp); if (c.ntfy_topic) await ntfyPush(c.ntfy_topic, `${staffer.screen_name} has a question`, q); } catch {}
            asked = true;
            out = 'question posted - the boss will click an answer; your turn ends here';
          }
        }
        else if (tu.name === 'calendar_read') out = (await gcalEvents(env, tp, Number(tu.input?.days))) ?? await calendarRead(env, tp, Number(tu.input?.days));
        else if (tu.name === 'gmail_unread') out = await gmailUnread(env, tp, Number(tu.input?.limit));
        else if (tu.name === 'yt_recent_comments') out = await ytRecentComments(env, tp, Number(tu.input?.limit));
        else if (tu.name === 'yt_reply') out = await ytReply(env, tp, String(tu.input?.parent_id || ''), String(tu.input?.text || ''));
        else if (tu.name === 'feed_read') out = await feedRead(env, tp, String(tu.input?.url || '') || undefined);
        else if (tu.name === 'notify_boss') {
          const c = await getConnectors(env, tp);
          out = await ntfyPush(c.ntfy_topic, staffer.screen_name, String(tu.input?.message || ''));
        }
        else if (tu.name === 'wallet_create') out = await walletCreate(env, tp, tu.input?.name);
        else if (tu.name === 'wallet_import') out = await walletImport(env, tp, tu.input?.name, tu.input?.private_key);
        else if (tu.name === 'wallet_list') out = await walletListText(env, tp);
        else if (tu.name === 'api_call') out = await apiCall(env, tp, tu.input?.connector, tu.input?.method, tu.input?.path, tu.input?.body);
        else if (tu.name === 'http_request') out = await httpRequest(tu.input?.url, tu.input?.method, tu.input?.body, tu.input?.headers);
        else if (tu.name === 'repo_commit') out = await repoCommit(env, tp, tu.input?.path, tu.input?.content, tu.input?.message);
        else if (tu.name === 'repo_read') out = await repoRead(env, tp, tu.input?.path);
        else if (tu.name === 'team_stats') out = JSON.stringify(await teamStats(env, tp));
        else if (tu.name === 'hire_staffer') out = deps.hireStaffer ? await deps.hireStaffer(env, tu.input || {}) : 'ERROR: hiring not available here';
        else if (tu.name === 'set_routine') {
          const target = deps.staff.find((s) => s.screen_name.toLowerCase() === String(tu.input?.staffer || '').toLowerCase());
          const h = Number(tu.input?.hourUTC);
          const evh = Number(tu.input?.every_hours);
          const txt = String(tu.input?.text || '').trim().slice(0, 1500);
          if (!target) out = `ERROR: no teammate named "${tu.input?.staffer}" - use list_team`;
          else if ((!(h >= 0 && h <= 23) && !(evh >= 2 && evh <= 12)) || !txt) out = 'ERROR: need the task text plus hourUTC 0-23 (daily) OR every_hours 2-12 (recurring)';
          else {
            const rk = `system/routines/${acctOf(tp)}.json`;
            const o = await env.FS.get(rk);
            const list = o ? JSON.parse(await o.text()) : [];
            if (list.length >= 10) out = 'ERROR: routine limit (10) reached - ask the boss to prune in the panel';
            else {
              const row = { id: Date.now().toString(36), staffer: target.screen_name, text: txt, from: staffer.screen_name, tp, lastRun: '' };
              if (evh >= 2 && evh <= 12) row.everyHours = evh; else row.hourUTC = h;
              list.push(row);
              await env.FS.put(rk, JSON.stringify(list));
              out = `routine set: ${target.screen_name} ${row.everyHours ? `every ${row.everyHours}h` : `daily at ${String(h).padStart(2, '0')}:00 UTC`} - "${txt.slice(0, 80)}"`;
            }
          }
        }
        else if (tu.name === 'coworker_report') {
          const target = deps.staff.find((s) => s.screen_name.toLowerCase() === String(tu.input?.name || '').toLowerCase());
          if (!target) out = `ERROR: no teammate named "${tu.input?.name}"`;
          else {
            const o = await env.FS.get(`${tp}threads/${target.screen_name.toLowerCase()}.jsonl`);
            const ms = o ? (await o.text()).split('\n').filter(Boolean).map((l) => JSON.parse(l)).slice(-8) : [];
            out = ms.length
              ? ms.map((m) => `${m.from}: ${m.body.slice(0, 180)}${m.verify ? ` [${m.verify.verdict.toUpperCase()}]` : ''}`).join('\n')
              : `${target.screen_name} has no recent thread activity`;
          }
        }
        else out = await deps.runTool(env, tu.name, tu.input || {});
      } catch (e) { out = `ERROR: ${e?.msg || e?.message || e}`; }
      if (!String(out).startsWith('ERROR')) {
        const tgt = tu.name === 'message_teammate' ? '→' + (tu.input?.to || '')
          : tu.name === 'api_call' ? ' ' + (tu.input?.connector || '')
          : /^fs_|^repo_/.test(tu.name) ? ' ' + String(tu.input?.path || tu.input?.prefix || '').slice(0, 40)
          : tu.name === 'browser_visit' || tu.name === 'web_fetch' || tu.name === 'http_request' ? ' ' + String(tu.input?.url || '').slice(0, 40)
          : tu.name === 'set_routine' ? ' ' + (tu.input?.staffer || '') : '';
        actionsLog.push(`${tu.name}${tgt}`);
      }
      results.push({ type: 'tool_result', tool_use_id: tu.id, content: String(out).slice(0, 4000) });
    }
    convo.push({ role: 'user', content: results });
    if (asked) break; // the ask IS the reply; the boss's click continues the thread
    if (round === MAX_ROUNDS - 1) finalText = texts || 'Ran out of tool rounds — here is where I got to; ask me to continue.';
  }
  // flush one-hop teammate wakes AFTER our own reply logic so the chain reads in order
  const flushWakes = async () => { if (deps.pending?.length) { const p = deps.pending.slice(); deps.pending.length = 0; await Promise.allSettled(p); } };
  if (asked) { await env.FS.delete(lockKey); await flushWakes(); return { staffer: staffer.screen_name, asked: true }; }
  // some brains (gpt-oss) end tool-heavy turns with empty content — real work must never vanish:
  // nudge once for a closing report, else report the ledger verbatim
  if (!finalText && actionsLog.length) {
    try {
      convo.push({ role: 'user', content: 'System: your tools ran but you sent no closing message. Give the team your report now, plain text, no tools.' });
      const r2 = await callBrain(env, systemPrompt(staffer, officeCtx), convo, staffer.brain, { toolList: [] });
      finalText = (r2.content || []).filter((c) => c.type === 'text').map((c) => c.text).join('\n').trim() || null;
    } catch {}
    if (!finalText) finalText = `Done. Ran: ${actionsLog.join(', ')}.`;
  }
  if (!finalText) { await env.FS.delete(lockKey); await flushWakes(); return null; }
  // individuality: the UI stamps who is speaking - strip any "Eli:" self-prefixes the model mimics
  finalText = finalText.replace(new RegExp(`^(\\s*${staffer.screen_name}\\s*:\\s*)+`, 'i'), '').trim() || finalText;
  const verify = await deps.appendToThread(env, who, staffer.screen_name, finalText, undefined, actionsLog);
  // ROUND-TRIP (Anthony 2026-08-14: "they can always return back when the other replies"): work a
  // teammate sent lands back in THEIR chat when answered. Reports don't echo (one round-trip).
  const requester = !last.report && deps.staff.find((s) => s.screen_name === last.from && s.screen_name !== staffer.screen_name);
  if (requester) {
    await deps.appendToThread(env, requester.screen_name.toLowerCase(), staffer.screen_name, finalText, undefined, actionsLog, true);
  }
  await env.FS.delete(lockKey); // working indicator off
  await flushWakes();
  // A STAMP IS A WORK ORDER (Anthony 2026-08-14: "reviewers must make it retry, not just fail"):
  // an unverified claim bounces straight back to its author for ONE bounded retry.
  // hit the round ceiling? one automatic continuation with fresh rounds - stalls need no human
  if (finalText.startsWith('Ran out of tool rounds') && !deps.retried) {
    await deps.appendToThread(env, who, 'Auditor', 'You hit the tool-round limit. You have a fresh set now - continue exactly where you left off and finish the job.');
    await respondForStaffer(env, { ...deps, retried: true, pending: [] }, staffer).catch(() => {});
  } else if (verify && verify.verdict === 'unverified' && !deps.retried) {
    const reason = verify.reason || `named files unchanged: ${(verify.checked || []).filter((c) => !c.changed).map((c) => c.path).join(', ')}`;
    await deps.appendToThread(env, who, 'Auditor', `Your last reply was stamped: ${reason}. Do the work FOR REAL now - run the tools, land the files, then report honestly. If you are genuinely blocked, say exactly what blocked you instead.`);
    // ESCALATION RETRY: the brain that just fabricated will fabricate again on the same thread -
    // the bounced retry runs on the office's strong fallback brain instead
    const strong = staffer.brain?.model === STRONG_FALLBACK.model ? staffer
      : { ...staffer, brain: { ...STRONG_FALLBACK } };
    await respondForStaffer(env, { ...deps, retried: true, pending: [] }, strong).catch(() => {});
  }
  return { staffer: staffer.screen_name, replied: true, verify };
  } finally {
    // a thrown brain call must never strand the staffer behind a stale lock (429 scar, 2026-08-14)
    await env.FS.delete(lockKey).catch(() => {});
  }
}

export async function runTick(env, deps) {
  const out = [];
  for (const staffer of deps.staff) {
    if (out.length >= MAX_STAFF_PER_TICK) break;
    try {
      const r = await respondForStaffer(env, deps, staffer);
      if (r) out.push(r);
    } catch (e) {
      out.push({ staffer: staffer.screen_name, error: String(e?.message || e).slice(0, 200) });
    }
  }
  return out;
}
